"""Import every model so ``Base.metadata`` is complete (Alembic autogenerate)."""

from kalshi_ai.db.models.accounts import (
    ActivationCode,
    ActivationCodeRedemption,
    AuditLog,
    ConnectToken,
    Disclosure,
    KalshiConnection,
    StripeCustomer,
    StripeEvent,
    Subscription,
    SubscriptionPlan,
    User,
)
from kalshi_ai.db.models.market_data import (
    DataPoint,
    Market,
    MarketSnapshot,
    NewsArticle,
    OrderBookSnapshot,
    SocialPost,
    SourceHealth,
    SystemEvent,
    SystemFlag,
)
from kalshi_ai.db.models.trading import (
    FeatureSnapshot,
    ModelVersion,
    Order,
    PaperAccount,
    PaperTrade,
    Position,
    Prediction,
    RiskSettings,
    Signal,
)

__all__ = [
    "ActivationCode",
    "ActivationCodeRedemption",
    "AuditLog",
    "ConnectToken",
    "DataPoint",
    "Disclosure",
    "FeatureSnapshot",
    "KalshiConnection",
    "Market",
    "MarketSnapshot",
    "ModelVersion",
    "NewsArticle",
    "Order",
    "OrderBookSnapshot",
    "PaperAccount",
    "PaperTrade",
    "Position",
    "Prediction",
    "RiskSettings",
    "Signal",
    "SocialPost",
    "SourceHealth",
    "StripeCustomer",
    "StripeEvent",
    "Subscription",
    "SubscriptionPlan",
    "SystemEvent",
    "SystemFlag",
    "User",
]
