"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-02 03:53:42.262843
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_points",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("metric", sa.String(length=64), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("reliability", sa.Float(), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "extra", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_points")),
    )
    op.create_index("ix_data_points_symbol_ts", "data_points", ["symbol", "ts"], unique=False)
    op.create_table(
        "disclosures",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body_markdown", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_disclosures")),
        sa.UniqueConstraint("slug", "version", name="slug_version"),
    )
    op.create_table(
        "features",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("market_ticker", sa.String(length=128), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("feature_set_version", sa.String(length=32), nullable=False),
        sa.Column(
            "features", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "data_versions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("feature_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_features")),
    )
    op.create_index("ix_features_ticker_ts", "features", ["market_ticker", "ts"], unique=False)
    op.create_table(
        "market_snapshots",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(length=128), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("yes_bid", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("yes_ask", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("no_bid", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("no_ask", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("last_price", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("volume", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("open_interest", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_snapshots")),
    )
    op.create_index("ix_market_snapshots_ticker_ts", "market_snapshots", ["ticker", "ts"], unique=False)
    op.create_table(
        "markets",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(length=128), nullable=False),
        sa.Column("event_ticker", sa.String(length=128), nullable=True),
        sa.Column("series_ticker", sa.String(length=64), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("yes_sub_title", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("asset_class", sa.String(length=32), nullable=False),
        sa.Column("open_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", sa.String(length=16), nullable=True),
        sa.Column("tick_size", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("raw", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_markets")),
        sa.UniqueConstraint("ticker", name=op.f("uq_markets_ticker")),
    )
    op.create_index(op.f("ix_markets_event_ticker"), "markets", ["event_ticker"], unique=False)
    op.create_index("ix_markets_series", "markets", ["series_ticker"], unique=False)
    op.create_index("ix_markets_status_close", "markets", ["status", "close_time"], unique=False)
    op.create_table(
        "model_versions",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "params", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column(
            "metrics", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column(
            "artifact", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_versions")),
        sa.UniqueConstraint("name", "version", name="name_version"),
    )
    op.create_table(
        "news",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("url_hash", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("cluster_id", sa.String(length=64), nullable=False),
        sa.Column("is_duplicate", sa.Boolean(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("sentiment", sa.Float(), nullable=False),
        sa.Column("relevance", sa.Float(), nullable=False),
        sa.Column("expected_direction", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "topics", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("reliability", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_news")),
        sa.UniqueConstraint("url_hash", name=op.f("uq_news_url_hash")),
    )
    op.create_index("ix_news_cluster", "news", ["cluster_id"], unique=False)
    op.create_index("ix_news_published_at", "news", ["published_at"], unique=False)
    op.create_table(
        "order_books",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(length=128), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "yes_levels", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "no_levels", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("best_yes_bid", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("best_yes_ask", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("spread", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("yes_depth", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("no_depth", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("imbalance", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_books")),
    )
    op.create_index("ix_order_books_ticker_ts", "order_books", ["ticker", "ts"], unique=False)
    op.create_table(
        "social_posts",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("author", sa.String(length=128), nullable=True),
        sa.Column("author_followers", sa.Integer(), nullable=True),
        sa.Column("author_age_days", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("engagement", sa.Integer(), nullable=False),
        sa.Column("sentiment", sa.Float(), nullable=False),
        sa.Column("spam_score", sa.Float(), nullable=False),
        sa.Column("bot_score", sa.Float(), nullable=False),
        sa.Column("is_duplicate", sa.Boolean(), nullable=False),
        sa.Column(
            "topics", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_social_posts")),
        sa.UniqueConstraint("platform", "external_id", name="platform_external"),
    )
    op.create_index("ix_social_posts_posted_at", "social_posts", ["posted_at"], unique=False)
    op.create_table(
        "source_health",
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("source", name=op.f("pk_source_health")),
    )
    op.create_table(
        "stripe_events",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=128), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stripe_events")),
    )
    op.create_table(
        "subscription_plans",
        sa.Column("plan", sa.String(length=32), nullable=False),
        sa.Column("interval", sa.String(length=32), nullable=False),
        sa.Column("stripe_price_id", sa.String(length=128), nullable=True),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("display_name", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_plans")),
        sa.UniqueConstraint("plan", "interval", name="plan_interval"),
        sa.UniqueConstraint("stripe_price_id", name=op.f("uq_subscription_plans_stripe_price_id")),
    )
    op.create_table(
        "system_events",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column(
            "details", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_events")),
    )
    op.create_index("ix_system_events_created_at", "system_events", ["created_at"], unique=False)
    op.create_table(
        "users",
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("telegram_username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("suspended_reason", sa.String(length=500), nullable=True),
        sa.Column("disclosures_accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disclosures_version", sa.String(length=32), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("telegram_user_id", name=op.f("uq_users_telegram_user_id")),
    )
    op.create_table(
        "activation_codes",
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("code_hint", sa.String(length=16), nullable=False),
        sa.Column("plan", sa.String(length=32), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=False),
        sa.Column("current_uses", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], name=op.f("fk_activation_codes_created_by_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activation_codes")),
        sa.UniqueConstraint("code_hash", name=op.f("uq_activation_codes_code_hash")),
    )
    op.create_index("ix_activation_codes_status", "activation_codes", ["status"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column(
            "details", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_audit_logs_actor_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index("ix_audit_logs_action", "audit_logs", ["action"], unique=False)
    op.create_index("ix_audit_logs_actor", "audit_logs", ["actor_user_id"], unique=False)
    op.create_index("ix_audit_logs_created_at", "audit_logs", ["created_at"], unique=False)
    op.create_table(
        "connect_tokens",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_connect_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connect_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_connect_tokens_token_hash")),
    )
    op.create_table(
        "kalshi_connections",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("environment", sa.String(length=32), nullable=False),
        sa.Column("encrypted_api_key_id", sa.LargeBinary(), nullable=False),
        sa.Column("encrypted_private_key", sa.LargeBinary(), nullable=False),
        sa.Column("api_key_id_hint", sa.String(length=16), nullable=False),
        sa.Column("public_key_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("key_type", sa.String(length=16), nullable=False),
        sa.Column(
            "scopes", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_kalshi_connections_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kalshi_connections")),
        sa.UniqueConstraint("user_id", name=op.f("uq_kalshi_connections_user_id")),
    )
    op.create_table(
        "paper_accounts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("starting_balance", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("cash_balance", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_paper_accounts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_accounts")),
        sa.UniqueConstraint("user_id", name=op.f("uq_paper_accounts_user_id")),
    )
    op.create_table(
        "positions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("market_ticker", sa.String(length=128), nullable=False),
        sa.Column("side", sa.String(length=32), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("avg_price", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("cost_basis", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("mark_price", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("realized_pnl", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_positions_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
        sa.UniqueConstraint("user_id", "mode", "market_ticker", "side", name="user_mode_market_side"),
    )
    op.create_index("ix_positions_user_status", "positions", ["user_id", "status"], unique=False)
    op.create_table(
        "predictions",
        sa.Column("market_ticker", sa.String(length=128), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("feature_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("model_version_id", sa.Uuid(), nullable=True),
        sa.Column("model_version", sa.String(length=96), nullable=False),
        sa.Column(
            "data_versions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("probability_yes", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("market_probability_yes", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("market_price_yes_ask", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("market_price_no_ask", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("edge", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("data_freshness_seconds", sa.Float(), nullable=True),
        sa.Column(
            "analysis", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("outcome_yes", sa.Boolean(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["feature_id"], ["features.id"], name=op.f("fk_predictions_feature_id_features")),
        sa.ForeignKeyConstraint(
            ["model_version_id"], ["model_versions.id"], name=op.f("fk_predictions_model_version_id_model_versions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_predictions")),
    )
    op.create_index("ix_predictions_resolved", "predictions", ["resolved_at"], unique=False)
    op.create_index("ix_predictions_ticker_ts", "predictions", ["market_ticker", "ts"], unique=False)
    op.create_table(
        "risk_settings",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("risk_mode", sa.String(length=32), nullable=False),
        sa.Column(
            "overrides", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("paper_trading_enabled", sa.Boolean(), nullable=False),
        sa.Column("auto_trading_enabled", sa.Boolean(), nullable=False),
        sa.Column("live_trading_enabled", sa.Boolean(), nullable=False),
        sa.Column("live_trading_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("risk_settings_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_risk_hash", sa.String(length=64), nullable=True),
        sa.Column("kill_switch_active", sa.Boolean(), nullable=False),
        sa.Column("kill_switch_activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("admin_auto_trading_disabled", sa.Boolean(), nullable=False),
        sa.Column(
            "market_allowlist",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("notify_signals", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_risk_settings_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_settings")),
        sa.UniqueConstraint("user_id", name=op.f("uq_risk_settings_user_id")),
    )
    op.create_table(
        "stripe_customers",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_stripe_customers_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stripe_customers")),
        sa.UniqueConstraint("stripe_customer_id", name=op.f("uq_stripe_customers_stripe_customer_id")),
        sa.UniqueConstraint("user_id", name=op.f("uq_stripe_customers_user_id")),
    )
    op.create_table(
        "system_flags",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column(
            "value", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_system_flags_updated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_system_flags")),
    )
    op.create_table(
        "signals",
        sa.Column("prediction_id", sa.Uuid(), nullable=False),
        sa.Column("market_ticker", sa.String(length=128), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("side", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("estimated_probability", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("market_probability", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("edge", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("confidence_level", sa.String(length=32), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("model_version", sa.String(length=96), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column(
            "reasons", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["prediction_id"], ["predictions.id"], name=op.f("fk_signals_prediction_id_predictions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signals")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_signals_idempotency_key")),
    )
    op.create_index("ix_signals_ticker_ts", "signals", ["market_ticker", "ts"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("plan", sa.String(length=32), nullable=False),
        sa.Column("interval", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=64), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(length=64), nullable=True),
        sa.Column("payment_status", sa.String(length=32), nullable=False),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activation_code_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["activation_code_id"],
            ["activation_codes.id"],
            name=op.f("fk_subscriptions_activation_code_id_activation_codes"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_subscriptions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint("stripe_subscription_id", name=op.f("uq_subscriptions_stripe_subscription_id")),
    )
    op.create_index("ix_subscriptions_expires_at", "subscriptions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_subscriptions_stripe_customer_id"), "subscriptions", ["stripe_customer_id"], unique=False)
    op.create_index("ix_subscriptions_user_status", "subscriptions", ["user_id", "status"], unique=False)
    op.create_table(
        "activation_code_redemptions",
        sa.Column("code_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=True),
        sa.Column("redeemed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["code_id"], ["activation_codes.id"], name=op.f("fk_activation_code_redemptions_code_id_activation_codes")
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_activation_code_redemptions_subscription_id_subscriptions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_activation_code_redemptions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activation_code_redemptions")),
        sa.UniqueConstraint("code_id", "user_id", name="code_user"),
    )
    op.create_table(
        "orders",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("signal_id", sa.Uuid(), nullable=True),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("market_ticker", sa.String(length=128), nullable=False),
        sa.Column("side", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=8), nullable=False),
        sa.Column("book_side", sa.String(length=8), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("yes_price", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("client_order_id", sa.String(length=64), nullable=False),
        sa.Column("kalshi_order_id", sa.String(length=64), nullable=True),
        sa.Column("filled_quantity", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("avg_fill_price", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("fees", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("risk_mode", sa.String(length=32), nullable=True),
        sa.Column("model_version", sa.String(length=96), nullable=True),
        sa.Column("estimated_probability", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("market_probability", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("edge", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "validation", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["signal_id"], ["signals.id"], name=op.f("fk_orders_signal_id_signals")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_orders_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("client_order_id", name=op.f("uq_orders_client_order_id")),
        sa.UniqueConstraint("user_id", "signal_id", "mode", name="user_signal_mode"),
    )
    op.create_index(op.f("ix_orders_kalshi_order_id"), "orders", ["kalshi_order_id"], unique=False)
    op.create_index("ix_orders_status", "orders", ["status"], unique=False)
    op.create_index("ix_orders_user_created", "orders", ["user_id", "created_at"], unique=False)
    op.create_index("ix_orders_user_market", "orders", ["user_id", "market_ticker"], unique=False)
    op.create_table(
        "paper_trades",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("market_ticker", sa.String(length=128), nullable=False),
        sa.Column("side", sa.String(length=32), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("fees", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("exit_price", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("pnl", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("estimated_probability", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("edge", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("risk_mode", sa.String(length=32), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name=op.f("fk_paper_trades_order_id_orders")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_paper_trades_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_trades")),
        sa.UniqueConstraint("order_id", name=op.f("uq_paper_trades_order_id")),
    )
    op.create_index("ix_paper_trades_user_opened", "paper_trades", ["user_id", "opened_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_paper_trades_user_opened", table_name="paper_trades")
    op.drop_table("paper_trades")
    op.drop_index("ix_orders_user_market", table_name="orders")
    op.drop_index("ix_orders_user_created", table_name="orders")
    op.drop_index("ix_orders_status", table_name="orders")
    op.drop_index(op.f("ix_orders_kalshi_order_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_table("activation_code_redemptions")
    op.drop_index("ix_subscriptions_user_status", table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_stripe_customer_id"), table_name="subscriptions")
    op.drop_index("ix_subscriptions_expires_at", table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index("ix_signals_ticker_ts", table_name="signals")
    op.drop_table("signals")
    op.drop_table("system_flags")
    op.drop_table("stripe_customers")
    op.drop_table("risk_settings")
    op.drop_index("ix_predictions_ticker_ts", table_name="predictions")
    op.drop_index("ix_predictions_resolved", table_name="predictions")
    op.drop_table("predictions")
    op.drop_index("ix_positions_user_status", table_name="positions")
    op.drop_table("positions")
    op.drop_table("paper_accounts")
    op.drop_table("kalshi_connections")
    op.drop_table("connect_tokens")
    op.drop_index("ix_audit_logs_created_at", table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor", table_name="audit_logs")
    op.drop_index("ix_audit_logs_action", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("ix_activation_codes_status", table_name="activation_codes")
    op.drop_table("activation_codes")
    op.drop_table("users")
    op.drop_index("ix_system_events_created_at", table_name="system_events")
    op.drop_table("system_events")
    op.drop_table("subscription_plans")
    op.drop_table("stripe_events")
    op.drop_table("source_health")
    op.drop_index("ix_social_posts_posted_at", table_name="social_posts")
    op.drop_table("social_posts")
    op.drop_index("ix_order_books_ticker_ts", table_name="order_books")
    op.drop_table("order_books")
    op.drop_index("ix_news_published_at", table_name="news")
    op.drop_index("ix_news_cluster", table_name="news")
    op.drop_table("news")
    op.drop_table("model_versions")
    op.drop_index("ix_markets_status_close", table_name="markets")
    op.drop_index("ix_markets_series", table_name="markets")
    op.drop_index(op.f("ix_markets_event_ticker"), table_name="markets")
    op.drop_table("markets")
    op.drop_index("ix_market_snapshots_ticker_ts", table_name="market_snapshots")
    op.drop_table("market_snapshots")
    op.drop_index("ix_features_ticker_ts", table_name="features")
    op.drop_table("features")
    op.drop_table("disclosures")
    op.drop_index("ix_data_points_symbol_ts", table_name="data_points")
    op.drop_table("data_points")
    # ### end Alembic commands ###
